export { default as About } from './about';
export { default as Blog } from './blog';
export { default as Contact } from './contact';
export { default as Error } from './error';
export { default as Home } from './home';
export { default as Layout } from './layout';
export { default as Lost } from './lost';
export { default as Projects } from './projects';
export { default as Services } from './services';
