name: Deploy FTP

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy-ftp:
    name: deploy-ftp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install
        run: yarn install --prefer-offline

      - name: Deploy App
        run: yarn deploy --scope=@apps/webfolio

      - name: Deploy FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          port: ${{ secrets.FTP_PORT }}
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./apps/webfolio/dist/
          server-dir: ./
          log-level: verbose
