name: Deploy Documentation

on:
  push:
    branches:
      - master
  pull_request:
    types: [edited]

jobs:
  docs:
    name: Docs
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    if: contains(github.event.pull_request.title, '#docs')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install
        run: yarn install --prefer-offline

      - name: Documentation
        run: yarn docs

      - name: Deploy Github Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: docs
          github-token: ${{ github.token }}
