name: 'Trigger Documentation'

on:
  issue_comment:
    types: [created]

jobs:
  docs:
    if: ${{ github.event.issue.pull_request }} && contains(github.event.comment.body, '/docs')
    uses: ./.github/workflows/docs.yml
