name: Documentation

on:
  push:
    branches:
      - master
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  documentation:
    runs-on: ubuntu-latest
    needs: ./.github/workflows/validate.yml
    steps:
      - run: yarn docs
      - uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: docs
          token: ${{ github.token }}
